#!/bin/bash
#
# Shell based bare_executor
#
# Bare executor is the simplest kind of executors for APIServers. This kind of
# executor interface just execute received commands in APIServer space and
# jobs are directly executed in 'target_info' directory.
#
# Infrastructure parameters
#
# user: <any value, unused>
#

# tools functions
. tools.sh

# logging import and customisation
LOG_FILE=sh_bare_executor.log
LOG_LEVEL=DEBUG
. logging.sh $LOG_FILE $LOG_LEVEL

# Check for compatibility issues before start the server is also may produce
# several aliases used by next includes (do not move this line)
check_compatibility

# database functions
. fgdb.sh

# tasks functions
. tasks.sh

# APIServer configurations, see shAPIerver.conf
. config.sh

# queue functions
.  queue.sh

#
# Handlers
#

# Interruption; <ctrl-c>
int_handler() {
  log WARN "User interruption detected"
  status="ABORTED"
  target_status="INTERRUPTED"
  exit 0
}
trap int_handler INT KILL

# Exit 
exit_handler() {
  log INFO "Terminating bare execution on task_id: $task_id"
  update_queue_record $task_id || exit 1
  cleanup_temp
}
trap exit_handler EXIT

# Error
error_handler() {
  log ERROR "Script error occurred"
  status="ABORTED"
  target_status="ERRORED"
  exit 1
}
trap error_handler ERR

#
# Functions
#

#
# SH Bare Executor Interface code
#

# Queue task_id
task_id=$1
verify_queued_task
[ $? -ne 0 ] &&\
  log debug "Task '"${task_id}"' verification failed" &&\
  exit 1;

# Retrieve queue record
case $action in
  "SUBMIT")
  # Job description parameter and file presence
  job_desc=$(cat $submit_json |\
             jq '.application.parameters[]|select(.param_name=="jobdesc")' |\
             jq -r .param_value)
  [ "${job_desc}" = "" ] &&\
    status="ABORTED" &&\
    log ERROR "No job description specified for task id: '"$task_id"' with action: '"$action"'" &&\
    exit 1
  [ ! -f $action_info_path"/"$job_desc ] &&\
    status="ABORTED" &&\
    log ERROR "No job description: '"$action_info_path"/"$job_desc"' available for task id: '"$task_id"' with action: '"$action"'" &&\
    exit 1
  # Task arguments
  TASK_ARGS=($(cat $submit_json | jq .arguments[]; ))
  # Go to the action_info_path
  BARE_EXE_INFO=$action_info_path/.sh_bare_executor
  touch $BARE_EXE_INFO
  # Extract action
  SHBE_EXECUTABLE=$(cat $action_info_path"/"$job_desc |\
                    grep -i "^executable" |\
                    awk -F'=' '{ print $2 }' |\
                    xargs echo)
  SHBE_ARGUMENTS=$(cat $action_info_path"/"$job_desc |\
                    grep -i "^arguments" |\
                    awk -F'=' '{ print $2 }' |\
                    xargs echo)" "${TASK_ARGS[@]}
  SHBE_STDOUT=$(cat $action_info_path"/"$job_desc |\
                    grep -i "^stdout" |\
                    awk -F'=' '{ print $2 }' |\
                    xargs echo)
  [ "$SHBE_STDOUT" = "" ] &&\
    SHBE_STDOUT=.stdout
  SHBE_STDERR=$(cat $action_info_path"/"$job_desc |\
                    grep -i "^stderr" |\
                    awk -F'=' '{ print $2 }' |\
                    xargs echo)
  [ "$SHBE_STDERR" = "" ] &&\
    SHBE_STDERR=.stderr
  # Output files are in the form (f1, f2, ... fn)
  SHBE_OUTFILES_VAL=$(cat $action_info_path"/"$job_desc |\
                    grep -i "^output_files" |\
                    awk -F'=' '{ print $2 }' |\
                    xargs echo)
  eval SHBE_OUTFILES"="$SHBE_OUTFILES_VAL
  log DEBUG "Job description"
  log DEBUG "\texecutable=$SHBE_EXECUTABLE"
  log DEBUG "\targuments=$SHBE_ARGUMENTS"
  log DEBUG "\toutput=$SHBE_STDOUT"
  log DEBUG "\terror=$SHBE_STDERR"
  log DEBUG "\toutput_files=$SHBE_OUTFILES_VAL"
  # Infrastructure parameters
  get_temp INFRA_PARAMS
  $(infra_parameters > $INFRA_PARAMS) ||\
    (log ERROR "Unable to get infrastructure parameters" &&\
    STATUS="ABORTED" &&\
    exit 1;)
  infra_user=$(cat $INFRA_PARAMS | grep ^user | awk -F'\t' '{ print $2 }')
  [ "$infra_user" = "" ] &&\
    infra_user=$(whoami) &&\
    log WARN "Unable to determine the infrastructure username parameter, using default: '"$infra_user"'"
  rm_temp INFRA_PARAMS
  # Execute the requested job
  log DEBUG "Executing: \"$SHBE_EXECUTABLE $SHBE_ARGUMENTS 2>$SHBE_STDERR >$SHBE_STDOUT\""
  echo "start_ts="$(ts) >> $BARE_EXE_INFO
  cd $action_info_path
  $SHBE_EXECUTABLE $SHBE_ARGUMENTS 2>$SHBE_STDERR >$SHBE_STDOUT &
  SHBE_PID=$!
  cd - >/dev/null
  status="RUNNING"
  target_status="RUNNING"
  target_id=$SHBE_PID
  echo "task_id=${SHBE_PID}" >> $BARE_EXE_INFO
  update_queue_record $task_id || exit 1
  log DEBUG "Waiting for execution completion"
  wait $SHBE_PID
  SHBE_RET=$?
  echo "end_ts="$(ts) >> $BARE_EXE_INFO
  echo "return_code=${SHBE_RET}" >> $BARE_EXE_INFO
  log DEBUG "Exit code: $SHBE_RET"
  [ $SHBE_RET -eq 0 ] &&\
    status="DONE" &&\
    target_status="DONE" ||\
    (status="ABORTED" &&\
    target_status="ABORTED";)
  finalize_task || exit 1
  ;;
  "STATUS")
  log DEBUG "Not yet implemented action: '"$action"' for task_id: '"$task_id"'"
  ;;
  "KILL")
  log DEBUG "Not yet implemented action: '"$action"' for task_id: '"$task_id"'"
  ;;
  *)
  log ERROR "Unknown action: '"$action"' for task_id: '"$task_id"'"
  exit 1
  ;;
esac

